version: '3.9'
services:
  angular:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"
    container_name: angular
    user: "${UID}:${GID}"
    volumes:
       - ./:/app